### ISSUE TITLE
DLESS command line argument issue

### ISSUE THREAD

**Issue by wadekj** [UCSantaCruzComputationalGenomicsLab/phast#1]
I am attempting to use DLESS to analyze alignment data from hg19 (46way) for regions associated with specific genes. However, while I have both the .mod and .maf files built for the multiz46way alignment, when I try to run DLESS according to its usage ($ dless -i MAF -M chr7.fa alignment.maf tree.mod > results.gff) I get the "Missing alignment file or model file.  Try 'dless -h'." error.

Interestingly, when I remove the alignment file and only use the .mod, this is the output:
"Reading tree model from tree.mod...
Reading alignment from tree.mod...
Unable to determine alignment format"

The same is true for when I replace the .mod with the .maf. It will successfully try to read it, but will obviously throw an error because it is the wrong file type.

I'm wondering if there is an issue with how the program is accepting arguments? When there is only one argument, it will accept the file, but then it tries to read both the tree information and the alignment information from that same file, which is not possible.

Is there an issue with the source code, or am I not executing it properly somehow?

Thanks,
Kristen Wade

**Comment by joelarmstrong** [comment]
Hi Kristen,

Apologies, this isn't actually the official PHAST repository, just a mirror that we cloned so we could incorporate it into progressiveCactus. We aren't the PHAST developers and I don't think anyone gets notifications for any issues that are opened here.

That said, by chance we ran into the same bug and found this issue on our old mirror! The bug has just been fixed by the PHAST devs at their official git repository:

https://github.com/CshlSiepelLab/phast

Very sorry for the confusion. I've updated this repo's README to be more clear that it's a mirror.
